### ISSUE TITLE
Macro support in RapidSmith 

### ISSUE THREAD

**Issue by ttown523** [byuccl/RapidSmith2#176]
The Vivado synthesis tool does not fully flatten all parts of a design. We need to either

1. Flatten the rest of the design on the TINCR side of things, or
2. Process the macro cells in RapidSmith, and flatten them on the RapidSmith side
3. Handle cell hierarchy in RapidSmith. 

Thoughts?

**Comment by nelsobe** [comment]
If the left-over macros are few and far between I am OK with a custom flattening process that is family-specific.  I sense that adding true hierarchy support into RS2 could be a ton of work for very little payback other than for this one issue.

I personally think that your 2nd option might be best since I assume it will be easier to program stuff in RS2 vs. Tcl.  Also, it might allow us to eventually enforce certain things so the user doesn't mess up the macro before exporting back to Vivado.
