### ISSUE TITLE
Unclear documentation for internalCellMap

### ISSUE THREAD

**Issue by trharoldsen** [byuccl/RapidSmith2#257]
variable internalCellMap says it is a list (it's not a list) of all internal cells in the design.  Can we better document what an internal cell is and how it differs from the other cell map so the user doesn't have to go figure out what it means.

**Comment by ttown523** [comment]
Did you read the Tech Report? Macro cells (and internal cells) are documented in the Designs section of the tech report. Users won't be looking at the source code, they should be looking at the tech report to learn this stuff. We can change the word "list" to "map" for developers, but otherwise this is well documented.
